name: match3
version: 0.0.3
description:
  A Dart port of the jMatch3 Game library
author: bruce davidson <brucedavidson@darkoverlordofdata.com>
homepage: https://github.com/darkoverlordofdata/match3
dependencies:

transformers:
- $dart2js:
    checked: false
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true