name: match3
version: 0.0.1
description:
  Match 3 Game Lib
author: brucedavidson <brucedavidson@darkoverlordofdata.com>
homepage: http://darkoverlordofdata.com
dependencies:

transformers:
- $dart2js:
    checked: false
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true